import { useEffect, useState } from "react";
import "./App.css";
import AppShell from "./components/AppShell";
import Modal from "./components/Modal";
import { changeCourseStatus, createCourse, createLesson, getCourse, listCourses, removeLesson, reorderCourseLessons, updateCourse, updateLesson as saveLesson } from "./services/courseService";
import { getDashboard, getInactivityAlerts, dismissInactivityAlert } from "./services/dashboardService";
import { bulkEnroll as bulkEnrollLearners, exportCourseProgress, selfEnroll as enrollSelf } from "./services/enrollmentService";
import { completeCourseLesson } from "./services/progressService";
import AlertsPage from "./pages/AlertsPage";
import AuthPage from "./pages/AuthPage";
import CourseDetailPage from "./pages/CourseDetailPage";
import CourseLibraryPage from "./pages/CourseLibraryPage";
import DashboardPage from "./pages/DashboardPage";
import MyLearningPage from "./pages/MyLearningPage";

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem("user") || "null")); const [token, setToken] = useState(() => localStorage.getItem("token")); const [page, setPage] = useState("dashboard");
  const [courses, setCourses] = useState([]); const [coursePagination, setCoursePagination] = useState(null); const [dashboard, setDashboard] = useState(null); const [alerts, setAlerts] = useState([]); const [query, setQuery] = useState("");
  const [filters, setFilters] = useState({ category: "", status: "", sortBy: "createdAt" }); const [selected, setSelected] = useState(null); const [notice, setNotice] = useState(""); const [modal, setModal] = useState(null); const [loading, setLoading] = useState(false); const [progressVersion, setProgressVersion] = useState(0); const [darkTheme, setDarkTheme] = useState(() => localStorage.getItem("theme") === "dark");
  const instructor = user?.role === "INSTRUCTOR"; const showNotice = (message) => { setNotice(message); setTimeout(() => setNotice(""), 3600); }; const logout = () => { localStorage.clear(); setToken(null); setUser(null); setPage("dashboard"); };
  const loadCourses = async () => { if (!token) return; setLoading(true); try { const data = await listCourses({ ...filters, search: query, limit: 9 }); setCourses(data.courses || []); setCoursePagination(data.pagination || null); } catch (error) { showNotice(error.response?.data?.message || "Could not load courses"); } finally { setLoading(false); } };
  const loadDashboard = async () => { if (instructor) { try { setDashboard((await getDashboard()).dashboard); } catch { /* dashboard may be unavailable until data is seeded */ } } }; const loadAlerts = async () => { if (instructor) { try { setAlerts((await getInactivityAlerts()).alerts || []); } catch { setAlerts([]); } } };
  useEffect(() => { loadCourses(); }, [token, filters, query]); useEffect(() => { if (token) { loadDashboard(); loadAlerts(); } }, [token, user]); useEffect(() => { document.documentElement.classList.toggle("dark-theme", darkTheme); localStorage.setItem("theme", darkTheme ? "dark" : "light"); }, [darkTheme]);
  const openCourse = async (course) => { try { setSelected((await getCourse(course.id)).course); setPage("course"); } catch (error) { showNotice(error.response?.data?.message || "Could not open course"); } };
  const saveCourse = async (form) => { try { const data = modal?.course ? await updateCourse(modal.course.id, form) : await createCourse(form); setModal(null); showNotice(data.message); loadCourses(); loadDashboard(); } catch (error) { showNotice(error.response?.data?.message || "Could not save course"); } };
  const courseAction = async (action) => { try { const data = await changeCourseStatus(selected.id, action); setSelected(data.course); showNotice(data.message); loadCourses(); } catch (error) { showNotice(error.response?.data?.message || "Action unavailable"); } }; const selfEnroll = async (courseId) => { try { showNotice((await enrollSelf(courseId)).message); } catch (error) { showNotice(error.response?.data?.message || "Could not enroll"); } };
  const addLesson = async (form) => { try { await createLesson(selected.id, form); setModal(null); await openCourse(selected); showNotice("Lesson added"); } catch (error) { showNotice(error.response?.data?.message || "Could not add lesson"); } }; const completeLesson = async (lesson) => { try { showNotice((await completeCourseLesson(lesson.id)).message); setProgressVersion((version) => version + 1); } catch (error) { showNotice(error.response?.data?.message || "Could not update progress"); } };
  const updateLesson = async (lessonId, form) => { try { const data = await saveLesson(lessonId, form); setSelected((course) => ({ ...course, lessons: course.lessons.map((lesson) => lesson.id === lessonId ? data.lesson : lesson) })); showNotice(data.message); } catch (error) { showNotice(error.response?.data?.message || "Could not update lesson"); } }; const deleteLesson = async (lessonId) => { if (!window.confirm("Delete this lesson?")) return; try { const data = await removeLesson(lessonId); setSelected((course) => ({ ...course, lessons: course.lessons.filter((lesson) => lesson.id !== lessonId).map((lesson, index) => ({ ...lesson, position: index + 1 })) })); showNotice(data.message); } catch (error) { showNotice(error.response?.data?.message || "Could not delete lesson"); } };
  const reorderLessons = async (lessonIds) => { try { const data = await reorderCourseLessons(selected.id, lessonIds); setSelected((course) => ({ ...course, lessons: data.lessons })); } catch (error) { showNotice(error.response?.data?.message || "Could not reorder lessons"); } }; const bulkEnroll = async (emails) => { try { return await bulkEnrollLearners(selected.id, emails); } catch (error) { throw new Error(error.response?.data?.message || "Could not enroll learners"); } };
  const exportProgress = async () => { try { const response = await exportCourseProgress(selected.id); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `${selected.title.replace(/[^a-z0-9]/gi, "_")}_progress.csv`; link.click(); URL.revokeObjectURL(url); } catch { showNotice("Could not export progress"); } };
  const title = page === "course" ? selected?.title : page === "alerts" ? "Inactivity alerts" : page === "learning" ? "My learning" : instructor ? `Good morning, ${user.name?.split(" ")[0]}` : "Find your next course";
  if (!token || !user) return <AuthPage onLogin={(data) => { localStorage.setItem("token", data.token); localStorage.setItem("user", JSON.stringify(data.user)); setToken(data.token); setUser(data.user); }}/>;
  return <><AppShell user={user} instructor={instructor} page={page} setPage={setPage} alerts={alerts} onLogout={logout} darkTheme={darkTheme} onToggleTheme={() => setDarkTheme(!darkTheme)} onCreateCourse={() => setModal({ type: "course" })} title={title}>{notice && <div className="notice">{notice}</div>}{page === "dashboard" && (instructor ? <DashboardPage data={dashboard} courses={courses} onBrowse={() => setPage("courses")}/> : <CourseLibraryPage courses={courses} loading={loading} filters={filters} setFilters={setFilters} query={query} setQuery={setQuery} pagination={coursePagination} open={openCourse} enroll={selfEnroll} learner/>)}{page === "courses" && <CourseLibraryPage courses={courses} loading={loading} filters={filters} setFilters={setFilters} query={query} setQuery={setQuery} pagination={coursePagination} open={openCourse}/>} {page === "learning" && <MyLearningPage open={openCourse}/>} {page === "alerts" && <AlertsPage alerts={alerts} dismiss={async (alert) => { await dismissInactivityAlert(alert.learnerId, alert.courseId); loadAlerts(); }}/>} {page === "course" && selected && <CourseDetailPage course={selected} instructor={instructor} progressVersion={progressVersion} back={() => setPage(instructor ? "courses" : "dashboard")} edit={() => setModal({ type: "course", course: selected })} addLesson={() => setModal({ type: "lesson" })} action={courseAction} enroll={selfEnroll} complete={completeLesson} updateLesson={updateLesson} deleteLesson={deleteLesson} reorderLessons={reorderLessons} bulkEnroll={bulkEnroll} exportProgress={exportProgress}/>}</AppShell>{modal && <Modal modal={modal} close={() => setModal(null)} save={modal.type === "lesson" ? addLesson : saveCourse}/>}</>;
}

export default App;
