import { useState } from "react";
import CommentActivity from "../components/CommentActivity";
import CompletionCertificate from "../components/CompletionCertificate";
import EnrollmentTools from "../components/EnrollmentTools";
import LearnerProgress from "../components/LearnerProgress";
import LessonEditor from "../components/LessonEditor";
import { date, nice } from "../utils/ui";

export default function CourseDetailPage({ course, instructor, progressVersion, back, edit, addLesson, action, enroll, complete, updateLesson, deleteLesson, reorderLessons, bulkEnroll, exportProgress }) {
  const [editing, setEditing] = useState(null);
  const move = (index, direction) => { const next = [...course.lessons]; const target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; reorderLessons(next.map((lesson) => lesson.id)); };
  const status = course.status?.toUpperCase();
  return <><button className="back" onClick={back}>Back to courses</button><section className="course-hero"><div><span className={`badge ${status?.toLowerCase()}`}>{nice(status)}</span><p className="category">{course.category}</p><h2>{course.title}</h2><p>{course.description}</p><small>Created {date(course.createdAt)} by {course.instructor?.name || "Instructor"}</small></div><div className="hero-actions">{instructor ? <><button className="secondary" onClick={edit}>Edit course</button>{status === "DRAFT" && <button className="primary" onClick={() => action("publish")}>Publish course</button>}{status === "PUBLISHED" && <button className="danger archive-button" onClick={() => action("archive")}>Archive course</button>}{status === "ARCHIVED" && <button className="primary" onClick={() => action("restore")}>Restore course</button>}</> : <button className="primary" onClick={() => enroll(course.id)}>Enroll in course</button>}</div></section>{!instructor && <><LearnerProgress courseId={course.id} version={progressVersion}/><CompletionCertificate course={course} version={progressVersion}/></>}{instructor && <EnrollmentTools bulkEnroll={bulkEnroll} exportProgress={exportProgress}/>}<section className="lesson-section"><div className="lesson-heading"><div><p className="eyebrow">CURRICULUM</p><h2>{course.lessons?.length || 0} lessons</h2></div>{instructor && <button className="secondary" onClick={addLesson}>+ Add lesson</button>}</div><div className="lessons">{course.lessons?.map((lesson, index) => <article className="lesson" key={lesson.id}><span className="lesson-number">{String(index + 1).padStart(2, "0")}</span><div className="lesson-copy"><h3>{lesson.title}</h3><p>{lesson.content}</p></div>{instructor ? <div className="lesson-actions"><button onClick={() => move(index, -1)} disabled={!index}>Up</button><button onClick={() => move(index, 1)} disabled={index === course.lessons.length - 1}>Down</button><button onClick={() => setEditing(lesson)}>Edit</button><button className="delete" onClick={() => deleteLesson(lesson.id)}>Delete</button></div> : <button className="complete" onClick={() => complete(lesson)}>Mark complete</button>}</article>)}</div>{!course.lessons?.length && <div className="empty-state">Add your first lesson before publishing this course.</div>}</section><CommentActivity courseId={course.id} instructor={instructor}/>{editing && <LessonEditor lesson={editing} save={async (form) => { await updateLesson(editing.id, form); setEditing(null); }} close={() => setEditing(null)}/>}</>;
}
